"""Shared analysis utilities for tear film spectrum processing."""

from .measurement_utils import (
    PreparedMeasurement,
    PreparedTheoreticalSpectrum,
    FFTArtifacts,
    load_txt_file_enhanced,
    load_measurement_spectrum,
    load_measurement_files,
    interpolate_measurement_to_theoretical,
    calculate_fit_metrics,
    detrend_signal,
    detect_peaks,
    detect_valleys,
    resample_uniform_grid,
    compute_fft,
    compute_fft_artifacts,
    prepare_measurement,
    prepare_theoretical_spectrum,
)
from .metrics import (
    MetricResult,
    SpectrumScore,
    peak_count_score,
    peak_delta_score,
    phase_overlap_score,
    residual_score,
    measurement_quality_score,
    temporal_continuity_score,
    composite_score,
    score_spectrum,
)

__all__ = [
    "PreparedMeasurement",
    "PreparedTheoreticalSpectrum",
    "FFTArtifacts",
    "MetricResult",
    "SpectrumScore",
    "load_txt_file_enhanced",
    "load_measurement_spectrum",
    "load_measurement_files",
    "interpolate_measurement_to_theoretical",
    "calculate_fit_metrics",
    "detrend_signal",
    "detect_peaks",
    "detect_valleys",
    "resample_uniform_grid",
    "compute_fft",
    "compute_fft_artifacts",
    "prepare_measurement",
    "prepare_theoretical_spectrum",
    "peak_count_score",
    "peak_delta_score",
    "phase_overlap_score",
    "residual_score",
    "measurement_quality_score",
    "temporal_continuity_score",
    "composite_score",
    "score_spectrum",
]
